### ISSUE TITLE
Interessted in how it works

### ISSUE THREAD

**Issue by novski** [yombo/yombo-gateway#1]
Hi im interrested in how this works. 
Are you willing to give answer/support?

**Comment by yombo** [comment]
Sure.  What are your questions?

**Comment by novski** [comment]
Great, let me ask some general Questions first:
1. What are your goals for this project?
and,
2. Why are you using laravel instead of django or a node.js solution?

**Comment by yombo** [comment]
1) I started this as a personal project a long time to ago accomplish two things: 1) Controlling my house and 2) learning Python. It's since grown up a bit and now it's starting to become being general purpose home automation. So, now my goal is to make it an easy to use home automation using a web interface to for setup, configuration, and some control. I want to also learn React/React Native/JavaScript, so I plan to make a mobile app using that. We will see. Right now I'm finishing up the core framework and building out the API in the gateway.

2) It's using Python 3.6 with using Twisted as a the framework. I choose Twisted as I originally started with Python 2.7 and Twisted was the best choice for me at the time. It's now compatible with both Twisted and Asyncio.

**Comment by yombo** [comment]
Started working on a document that describes the Yombo gateway and how it works.

**Comment by yombo** [comment]
Hello,
  Sorry for the delay. We're redoing the backend right now and will be tackling the front end. It's currently not working, give us a couple weeks and look for version 0.24.0.
  In short: Yes. You can install the software at multiple locations (within the same house or between houses/locations) and it will act as a single system. Whenever something takes place at one location, the other locations will know about this and can perform actions. For example, motion detected at location 1, location 2 can turn on a light, GPIO port, etc.
  This communication takes place over MQTT (with TLS encrytion signed by letsencrypt) and requires one of the locations to allow incoming port forwarding.
  This can all run on a Raspberry PI in each location.  Cheers.
